# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6
  
 script: ./civic.sh
  
#asdad
# Commands to be run before your environment runs.
before_script:
  - composer self-update